src/Entity/Annonce.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnnonceRepository")
 * @ORM\Table(name="symbnb_annonce")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"title"}, message="Une autre annonce possède déjà ce titre, merci de le modifier"
 * )
 */
class Annonce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères", maxMessage="Le titre ne doit pas faire plus de 255 caractères" )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire au moins 20 caractère")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre introduction doit faire au moins 100 caractère")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url( )
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="annonce", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="annonce")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="annonce", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug !
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return  void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer le commentaire d'un autheur par rapport à une annonce
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if($comment->getAuthor() === $author ) return $comment;
        }

        return null;
    }


    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     * @return float|int
     */
    public function getAvgRatings()
    {
        //Calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        });

        //Faire la division pour avoir la moyenne
        if (count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonces
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            //Calculer les jours qui se trouvent entre la date d'arrivée et de départ
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            $days = array_map(function ($dayTimeStamp) {
                return new \DateTime(date('Y-m-d', $dayTimeStamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAnnonce($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAnnonce() === $this) {
                $image->setAnnonce(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAnnonce($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAnnonce() === $this) {
                $booking->setAnnonce(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAnnonce($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAnnonce() === $this) {
                $comment->setAnnonce(null);
            }
        }

        return $this;
    }
}

src/Form/AnnonceType.php
<?php

namespace App\Form;

use App\Entity\Annonce;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class AnnonceType extends ApplicationType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration('Titre', "Un super titre"))
            ->add('slug', TextType::class, $this->getConfiguration("addresse web", "Tapez l'adresse web (automatique)", ['required' => false]))
            ->add('coverImage', UrlType::class, $this->getConfiguration("Url de l'image principale", "Donnez l'adresse d'une image qui donne vraiment envie"))
            ->add('introduction', TextType::class, $this->getConfiguration("Introduction", "Donnez la description globale de l'annonce"))
            ->add('content', TextareaType::class, $this->getConfiguration("Description détaillé", "Tapez une description qui donne vraiment envie de venir chez vous !"))
            ->add('rooms', IntegerType::class, $this->getConfiguration("Nombre de chambre", "Le nombre de chambre disponibles"))
            ->add('price', MoneyType::class, $this->getConfiguration("Prix par nuit", "Indiquez le prix que vous voulez pour une nuit"))
            ->add('images',
                CollectionType::class,
                [
                    'entry_type' => ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true,
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Annonce::class,
        ]);
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Form\AnnonceType;
use App\Repository\AnnonceRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Annonce;

class AnnonceController extends AbstractController
{
    /**
     * @Route("/annonce", name="annonce_index")
     */
    public function index(AnnonceRepository $repository)
    {
        $annonces = $repository->findAll();

        return $this->render('annonce/index.html.twig', [
            'annonces' => $annonces,
        ]);
    }

    /**
     * Permet de créer une annonce
     *
     * @Route("/annonce/new", name="annonce_create")
     *
     * @IsGranted("ROLE_USER")
     *
     * @return Response
     */
    public function create(Request $request, ObjectManager $manager)
    {
        $annonce = new Annonce();

        $form = $this->createForm(AnnonceType::class, $annonce);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            forEach ($annonce->getImages() as $image) {
                $image->setAnnonce($annonce);
                $manager->persist($image);
            }

            $annonce->setAuthor($this->getUser());

            $manager->persist($annonce);
            $manager->flush();


            $this->addFlash(
                'success',
                "Félicitation ! L'annonce <strong>{$annonce->getSlug()}test</strong> à bien été enregistrée !");

            return $this->redirectToRoute('annonce_show', [
                'slug' => $annonce->getSlug()
            ]);
        }


        return $this->render('annonce/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher une seule annonce
     *
     * @Route("/annonce/{slug}", name="annonce_show")
     * @return Response
     */
    public function show(Annonce $annonce)
    {
        //Je récupère l'annonce qui correspond au slug !

        return $this->render('annonce/show.html.twig', [
            'annonce' => $annonce
        ]);
    }

    /**
     * Permet d'afficher un formulaire d'édition
     *
     * @Route("/annonce/{slug}/edit", name="annonce_edit")
     * @Security("is_granted('ROLE_USER') and user === annonce.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     *
     *
     * @param Annonce $annonce
     * @param Request $request
     * @param ObjectManager $manager
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function edit(Annonce $annonce, Request $request, ObjectManager $manager)
    {

        $form = $this->createForm(AnnonceType::class, $annonce);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            forEach ($annonce->getImages() as $image) {
                $image->setAnnonce($annonce);
                $manager->persist($image);
            }

            $manager->persist($annonce);
            $manager->flush();


            $this->addFlash(
                'success',
                "Félicitation ! L'annonce <strong>{$annonce->getSlug()}test</strong> à bien été modifiée !");
            return $this->redirectToRoute('annonce_show', [
                'slug' => $annonce->getSlug()
            ]);
        }
        return $this->render('annonce/edit.html.twig', [
            'form' => $form->createView(),
            'annonce' => $annonce
        ]);
    }


    /**
     * Permet de supprimer une annonce
     *
     * @Route("/annonce/{slug}/delete" , name="annonce_delete")
     * @Security("is_granted('ROLE_USER') and user == annonce.getAuthor()", message="Vous n'avez pas le droit d'acceder à cette ressource")
     *
     *
     * @param Annonce $annonce
     * @param ObjectManager $manager
     *
     * @return Response
     */
    public function delete(Annonce $annonce, ObjectManager $manager){
        $manager->remove($annonce);
        $manager->flush();

        $this->addFlash("success", "L'annonce <strong>{$annonce->getTitle()}</strong> à bien été supprimée !");

        return $this->redirectToRoute("annonce_index");
    }

}

templates/annonce/_annonce.html.twig
{% set url = path('annonce_show' , {'slug' : annonce.slug}) %}
<div class="col-md-4">
	<div class="card bg-light mb-3">
		<div class="card-header text-center">
			{{ annonce.rooms }} chambres, <strong>{{ annonce.price | number_format(2, ',', ' ')}}&euro; / nuit</strong><br>
			{% if annonce.comments | length > 0 %}
				{% include 'partials/rating.html.twig' with {'rating' : annonce.avgRatings} %}
			{% else %}
				<small>Pas encore noté</small>
			{% endif %}
		</div>
		
		<a href="{{ url }}"><img src="{{ annonce.coverImage }}" alt="Image de l'appartement"
		                         style="height: 200px; width: 100%; display: block;"></a>
		<div class="card-body">
			<h4 class="card-title"><a href="{{ url }}">{{ annonce.title }}</a></h4>
			<p class="card-text">{{ annonce.introduction }}</p>
			<a href="{{ url }}" class="btn btn-primary float-right">En savoir plus</a>
			{% if app.user and app.user == annonce.author %}
				<a href="{{ path('annonce_edit', {'slug' : annonce.slug}) }}" class="btn btn-secondary">Modifier
					l'annonce</a>
				<a href="{{ path('annonce_delete', {'slug' : annonce.slug} ) }}" class="btn btn-danger"
				   onclick="return confirm(`Êtes-vous sûr de vouloir supprimer l'annonce : {{ annonce.title }} ?`)">Supprimer
					l'annonce</a>
			{% endif %}
		</div>
	</div>
</div>

templates/annonce/_collection.html.twig
{% block _annonce_images_widget %}
    <p>Ici vous pouvez ajouter vos propres images !</p>

    {{ form_widget(form) }}

    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
        <button type="button" id="annonce_image" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Ajouter une image
        </button>
    </div>
{% endblock %}

{% block _annonce_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _annonce_images_entry_widget %}


    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-5">
                {{ form_widget(form.url) }}
                {{ form_errors(form.url) }}
            </div>
            <div class="col-5">
                {{ form_widget(form.caption) }}
                {{ form_errors(form.caption) }}
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">&#10008;</button>
            </div>
        </div>
    </div>

{% endblock %}

templates/annonce/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une annonce{% endblock %}

{% form_theme form 'annonce/_collection.html.twig' %}

{% block body %}

    <div class="container">
        <h1>Modification de l'annonce : {{ annonce.title }}</h1>

        {{ form_start(form) }}
        {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
        {{ form_end(form) }}
    </div>

{% endblock %}


{% block javascripts %}

    <script src="{{ asset('build/js/annonce.js') }}"></script>

{% endblock %}

templates/annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces{% endblock %}

{% block body %}

    <div class="container">

        <h1 class="my-5">Voici les annonces de nos hôtes !</h1>
        <div class="row">
            {% for annonce in annonces %}
	            {% include 'annonce/_annonce.html.twig' %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/annonce/new.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'annonce/_collection.html.twig' %}

{% block body %}
	<div class="container">
		<h1 class="my-5">Créer une nouvelle annonce</h1>
		
		{{ form_start(form) }}
		
		<div class="row">
			<div class="col">
				<div class="alert alert-light">
					<h2>Informations générales</h2>
					<hr>
					{{ form_row(form.title) }}
					{{ form_row(form.slug) }}
					{{ form_row(form.price) }}
					{{ form_row(form.rooms) }}
				</div>
				<div class="alert alert-light">
					<h2>Détails de l'annonce</h2>
					<hr>
					{{ form_row(form.introduction) }}
					{{ form_row(form.content) }}
				</div>
			</div>
			<div class="col">
				<div class="alert alert-light">
					<h2>Images de l'annonce</h2>
					<hr>
					{{ form_row(form.coverImage) }}
					{{ form_row(form.images) }}
				</div>
			</div>
		</div>
		
		<div class="alert alert-success clearfix">
			<h2 class="alert-heading">Sauvegarder mon annonce</h2>
			<p>Vous êtes sur le point de créer votre annonce, nous sommes super fier de vous !</p>
			<button type="submit" class="btn btn-primary float-right">
				<i class="fas fa-check"></i>
				Créer nouvelle annonce
			</button>
		</div>
		{{ form_end(form) }}
	</div>
{% endblock %}


{% block javascripts %}
	
	<script src="{{ asset('build/js/annonce.js') }}"></script>

{% endblock %}

templates/annonce/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	{{ annonce.title }}
{% endblock %}

{% block body %}
	
	<div class="annonce-title" style="background-image: url({{ annonce.coverImage }})">
		<div class="container">
			<h1>{{ annonce.title }}</h1>
			<p>{{ annonce.introduction }}</p>
			
			<p class="h2">
				<strong>{{ annonce.rooms }} chambres</strong> pour <strong>{{ annonce.price | number_format(2 ,',',' ') }}&euro;</strong> par nuit
			</p>
			<a href="{{ path('booking_create', {'slug' : annonce.slug}) }}" class="btn btn-primary">Réserver</a>
			{% if app.user and app.user == annonce.author %}
				<a href="{{ path('annonce_edit', {'slug' : annonce.slug}) }}" class="btn btn-secondary">Modifier
					l'annonce</a>
				<a href="{{ path('annonce_delete', {'slug' : annonce.slug} ) }}" class="btn btn-danger"
				   onclick="return confirm(`Êtes-vous sûr de vouloir supprimer l'annonce : {{ annonce.title }} ?`)">Supprimer
					l'annonce</a>
			{% endif %}
		</div>
	</div>
	
	<div class="container">
		<div class="row">
			<div class="col-md-8 mb-3">
				{{ annonce.content | raw }}
				
				<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
					<ol class="carousel-indicators">
						{% for image in annonce.images %}
							<li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}"
							    class="{% if loop.first %}active{% endif %}"></li>
						{% endfor %}
					</ol>
					<div class="carousel-inner">
						{% for image in annonce.images %}
							<div class="carousel-item {% if loop.first %}active{% endif %}">
								<img class="d-block w-100" src="{{ image.url }}"
								     alt="First slide">
								<div class="carousel-caption d-none d-md-block">
									<h5>{{ annonce.title }}</h5>
									<p>{{ image.caption }}</p>
								</div>
							</div>
						{% endfor %}
					
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
				
				<hr>
				
				{% if annonce.comments | length >0 %}
					<h2 class="mb-3">Commentaires de nos voyageurs : </h2>
					
					<div class="alert alert-info">
						<h4 class="alert-heading text-center">
							<div class="row align-items-center">
								<div class="col">
									Note globale donnée par nos voyageurs
								</div>
								<div class="col">
									{% include 'partials/rating.html.twig' with {'rating' : annonce.avgRatings} %}
									<br>
									<small>(Calculée sur {{ annonce.comments | length }} avis)</small>
								</div>
							</div>
						</h4>
					</div>
					
					{% for comment in annonce.comments %}
					<div class="bg-light rounded mb-3 py-3 px-3">
						<strong>{{ comment.author.firstName }}</strong> a dit :
						<blockquote>
							{{ comment.content }}
						</blockquote>
						<strong>Note donnée : </strong>
						
						{% include 'partials/rating.html.twig' with {'rating' : comment.rating} %}
					</div>
					{% endfor %}
				{% else %}
					
					<h2>Cette annonce n'a pas encore reçu de commentaires ...</h2>
				
				{% endif %}
			
			</div>
			<div class="col">
				{% set a = annonce.author %}
				<div class="row">
					<div class="col-3">
						<a href="{{ path('user_show', {'slug' : a.slug}) }}">
							<img src="{{ annonce.author.picture }}" class="avatar avatar-medium"
							     alt="Avatar de {{ a.fullName }}">
						</a>
					</div>
					<div class="col">
						<a href="{{ path('user_show', {'slug' : a.slug}) }}">
							<h3>{{ a.fullName }}</h3>
						</a>
						<span class="badge badge-primary">{{ a.annonces | length }} annonces</span>
					</div>
				</div>
				{{ a.description | raw }}
			</div>
		</div>
	</div>

{% endblock %}