src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\Table(name="symbnb_booking")
 * @ORM\HasLifecycleCallbacks()
 */

class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Annonce", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $annonce;

    /**
     * @Assert\Date(message="Attention, la date d'arrivée doit être au bon format")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui !", groups={"front"})
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être ultérieur à la date d'arrivée !")
     * @Assert\Date(message="Attention, la date de départ doit être au bon format")
     * @ORM\Column(type="datetime")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * callback appelé à chaque fois qu'on créé une réservation
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function prePersist() {
        if(empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if(empty($this->amount)){
            //Prix de l'annonce * nombre de jour
            $this->amount =  $this->annonce->getPrice() * $this->getDuration();
        }

    }

    public function isBookableDates(){
        // 1) Il faut connaître les dates qui sont impossible pour l'annonce
        $notAvailableDays = $this->annonce->getNotAvailableDays();
        //2) Il faut comparer les dates choisies avec les dates impossibles
        $bookingDays = $this->getDays();

        $formatDay   = function($day){
            return $day->format('Y-m-d');
        };

        // Tableau de chaînes de caractères de mes journées
        $days            = array_map($formatDay, $bookingDays);
        $notAvailable    = array_map($formatDay, $notAvailableDays);

        foreach($days as $day){
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;

    }

    /**
     * Cette fonction va permetttre de récupérer un tableau des journées qui correspondent à ma réservation
     *
     * @return array Un tableau d'objets DateTime représentant les jours de la réservation
     */
    public function getDays(){

        $resultat = range(
          $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24*60*60
        );

        $days = array_map(function($dayTimestamp){
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;

    }

    public function getDuration() {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAnnonce(): ?Annonce
    {
        return $this->annonce;
    }

    public function setAnnonce(?Annonce $annonce): self
    {
        $this->annonce = $annonce;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping\JoinTable;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="symbnb_user")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Un autre utilisateur s'est déjà inscrit avec cette adresse email merci de la modifier !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez donner une URL valide pour votre avatar !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Vous n'avez pas correctement confirmé votre mot de passe")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="10", minMessage="Votre introduction doit faire au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="100", minMessage="Votre introduction doit faire au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Annonce", mappedBy="author")
     */
    private $annonces;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     * @JoinTable(name="symbnb_user_role")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;


    public function getFullName(){
        return "{$this->getFirstName()} {$this->getLastName()}";
    }
    
    /**
     * Permet d'initialiser le slug !
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return  void
     */
    public function initializeSlug() {
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName. ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
        $this->roles = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Annonce[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setAuthor($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->contains($annonce)) {
            $this->annonces->removeElement($annonce);
            // set the owning side to null (unless already changed)
            if ($annonce->getAuthor() === $this) {
                $annonce->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return array('ROLE_USER');
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {

        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword()
    {
        return $this->hash;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->getEmail();
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }


}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    /**
     * @Route("/annonce/{slug}/book", name="booking_create")
     * @param Annonce $annonce
     * @IsGranted("ROLE_USER")
     * @return Response
     */
    public function book(Annonce $annonce, Request $request, ObjectManager $manager)
    {
        $booking = new Booking();

        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $booking->setBooker($user)
                ->setAnnonce($annonce);

            //Si les dates ne sont pas disponibles, message d'erreur
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    "Les dates que vous avez choisi ne peuvent être réservées: elles sont déjà prises."
                );
            } else {
                //Sinon, enregistrement
                $manager->persist($booking);

                $manager->flush();

                return $this->redirectToRoute('booking_show', [
                    'id' => $booking->getId(),
                    'withAlert' => true
                ]);

            }

        }


        return $this->render('booking/book.html.twig', [
            'annonce' => $annonce,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher la page d'une réservation
     *
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     * @param Request $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function show(Booking $booking, Request $request, ObjectManager $manager)
    {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $comment->setAnnonce($booking->getAnnonce())
                ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash('success', 'Félicitations ! Votre commentaire à bien été pris en compte !');
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce: {{ annonce.title }}{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet"
	      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css"/>
{% endblock %}

{% block body %}
	<div class="container">
		
		<h1>Réservez pour l'annonce: <em>{{ annonce.title }}</em></h1>
		
		<p>Vous êtes sur le point de réserver le bien de <strong>{{ annonce.author.fullName }}</strong>, dites nous tout
			on s'occupe du reste !</p>
		
		
		{{ form_start(form) }}
		
		<div class="alert alert-light">
			
			<h2 class="h4">Commencer par nous dire quelles sont les dates qui vous intéressent !</h2>
			
			<div class="row">
				<div class="col">{{ form_row(form.startDate) }}</div>
				<div class="col">{{ form_row(form.endDate) }}</div>
			</div>
			
			<h4 class="mt-2">Montant du séjour : <span id="amount">...</span> &euro;</h4>
			<span id="days">0</span> nuit(s) à {{ annonce.price | number_format(2, ',', ' ') }} &euro; par nuit
			
			<h4 class="mt-3">Vous avez un commentaire ?</h4>
			
			{{ form_row(form.comment) }}
			
		</div>
		
		
		<h2>Vous avez terminé !</h2>
		<p>Vacances de rêve ? Hébergement pour le boulot ? Peu importe, on est avec vous !</p>
		
		<button type="submit" class="btn btn-success">Je réserve !</button>
		
		{{ form_end(form) }}
	
	</div>

{% endblock %}

{% block javascripts %}
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
	
	<script>
        $(document).ready(function () {
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
					{% for day in annonce.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
					{% endfor %}
                ],
                startDate: new Date()

            });

            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });
        
        function calculateAmount() {
            // On chope les dates
	        const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
	        const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
	        console.log(endDate);
	        console.log(startDate);
	        
	        if(startDate && endDate && startDate < endDate){
	            const DAY_TIME = 24 * 60 * 60 * 1000;
	            const interval = endDate.getTime() - startDate.getTime();
	            const days = interval / DAY_TIME;
	            const amount = days * {{ annonce.price }};
	            
	            $('#days').text(days);
	            $('#amount').text(amount.toLocaleString('fr-FR'));
	        }
        }
	</script>

{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{ booking.id }}{% endblock %}

{% block body %}
	
	{% set annonce = booking.annonce %}
	{% set author = annonce.author %}
	
	<div class="container">
		<h1 class="my-5">Votre réservation (n°{{ booking.id }})</h1>
		
		{% if app.request.query.get('withAlert') %}
			<div class="alert alert-success">
				<h4 class="alert-heading">Bravo !</h4>
				<p>
					Votre réservation auprès de <strong> <a
								href="{{ path('user_show', {'slug' : author.slug }) }}">{{ author.fullName }}</a></strong>
					pour l'annonce <strong><a
								href="{{ path('annonce_show', {'slug' : annonce.slug}) }}">{{ annonce.title }}</a></strong>,
					à bien été prise en compte !
				
				</p>
			</div>
		{% endif %}
		
		<div class="row">
			<div class="col">
				<div class="alert alert-light">
					<h2>Détails</h2>
					<dl class="row">
						<dt class="col-md-4">Numéro</dt>
						<dd class="col-md-8">{{ booking.id }}</dd>
						<dt class="col-md-4">Date d'arrivée</dt>
						<dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
						<dt class="col-md-4">Date de départ</dt>
						<dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
						<dt class="col-md-4">Nombre de nuits</dt>
						<dd class="col-md-8">{{ booking.duration }}</dd>
						<dt class="col-md-4">Montant total</dt>
						<dd class="col-md-8">{{ booking.amount | number_format(2, ',', ' ') }} &euro;</dd>
						<dt class="col-md-4">Commentaire</dt>
						<dd class="col-md-8">{{ booking.comment | default('Aucun Commentaire') }}</dd>
					</dl>
					
					<hr>
					
					<h2 class="alert-heading">Votre hôte</h2>
					<div class="row">
						<div class="col-3">
							<img src="{{ author.picture }}" class="avatar avatar-medium" alt="{{ author.fullName }}">
						</div>
						<div class="col-9">
							<h4><a href="{{ path('user_show', {'slug' : author.slug}) }}">{{ author.fullName }}</a></h4>
							
							<span class="badge badge-primary">{{ author.annonces |length }} annonces</span>
						</div>
						<div class="container">
							{{ author.description | raw }}
							
							<a href="{{ path('user_show', {'slug' : author.slug}) }}" class="btn btn-primary">Plus
								d'info sur {{ author.firstName }}</a>
						</div>
						
						<div class="alert alert-light" id="comment">
							<h2 class="alert-heading">Votre avis compte !</h2>
							{% if date() > date(booking.endDate) %}
								{% set comment = booking.annonce.commentFromAuthor(app.user) %}
								{% if comment is not null %}
									<blockquote>{{ comment.content }}</blockquote>
									<strong>Note : </strong> {% include 'partials/rating.html.twig' with {'rating' : comment.rating} %}
								{% else %}
									{{ form_start(form) }}
									{{ form_widget(form) }}
									<button type="submit" class="btn btn-success">Confirmer !</button>
									{{ form_end(form) }}
								{% endif %}
							
							{% else %}
								<p>Vous ne pourrez pas noter cette annonce tant que votre voyage ne sera pas complet</p>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="alert alert-light">
					<h2 class="alert-heading">Votre hébergement</h2>
					
					
					<h4><a href="{{ path('annonce_show', { 'slug' : annonce.slug }) }}">{{ annonce.title }}</a></h4>
					
					<img src="{{ annonce.coverImage }}" alt="Image de {{ annonce.title }}" class="img-fluid">
					
					<div class="container">
						{{ annonce.content | raw }}
					</div>
					
					<a href="{{ path('annonce_show', { 'slug': annonce.slug }) }}" class="btn btn-primary">Plus
						d'informations</a>
				</div>
			</div>
		</div>
	</div>

{% endblock %}